name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas

      - name: Run MLflow Project (Training Model)
        run: |
          cd MLProject
          mlflow run . --env-manager local

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image via MLflow
        run: |
          cd MLProject
          mlflow models build-docker -m "model_siap_docker" -n "${{ secrets.DOCKERHUB_USERNAME }}/parfumemodel:latest" --enable-mlserver --python-version 3.10
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/parfumemodel:latest"
